### ISSUE TITLE
AIFH-Vol3-Core not compilable (in VS2012)

### ISSUE THREAD

**Issue by tomseidel** [jeffheaton/aifh#30]
Bought the book Vol3 and tried to use the examples. However I cant compile the source-code with VS2012 While getting errors for:

RandomMOdelSelection.cs:
"public IGenerateRandom Random { get; set; } = new MersenneTwisterGenerateRandom();"

ResilientPropagation.cs:
"public double LastError { get; private set; } = 1.0;"

BoltzmannMachine.cs:
"public override double[] LongTermMemory => new double[0];"

Thanks for helping out.
Thomas

**Comment by jeffheaton** [comment]
I just checked in some changes that will make the code compile in VS2012.  I still want to check out a few more things before closing this issue.  I did not realize I had broken VS2012 comparability, thank you for bringing that to my attention.  Also thank you for buying the book!

**Comment by tomseidel** [comment]
Thanks Jeff for the quick fix. Not sure thou whether everthing works as intended.
For instance after trying "LearnDigitsConv", the code goves me no improvements after each iteration on the validation error. Is that inteded for this sample?

![image](https://cloud.githubusercontent.com/assets/9019688/12079996/e0b29f8c-b24c-11e5-850b-15dc85741f43.png)

Also the "LearnDigitsBackprop" does not converge to something meaningful after those 5 iterations.

Thanks for the great work anyway!

**Comment by jeffheaton** [comment]
That does not sound right, I am looking into that!

**Comment by jeffheaton** [comment]
This is related to a similar issue that I've been looking into, see issue #31 for more details.  I am going to close this issue, as comparability with VS2012 has been restored.  I am also going to update the readme files to indiciate that VS2012 is the minimally supported version.
