### ISSUE TITLE
error  in  example_xor.py

### ISSUE THREAD

**Issue by Sandy4321** [jeffheaton/aifh#34]
File "C:\Sander\my_code\aifh-master\vol3\vol3-python-examples\examples\example_xor.py", line 31, in <module>
  from nolearn.lasagne import NeuralNet
File "C:\Anaconda\Lib\site-packages\nolearn\lasagne.py", line 11, in <module>
  from lasagne.objectives import mse

ImportError: cannot import name mse

I use windows pc

and have all needed packages for nolearn pls see 
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Sander>pip install nolearn
Requirement already satisfied (use --upgrade to upgrade): nolearn in c:\anaconda
\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): gdbn in c:\anaconda\li
b\site-packages (from nolearn)
Requirement already satisfied (use --upgrade to upgrade): docopt in c:\anaconda\
lib\site-packages (from nolearn)
Requirement already satisfied (use --upgrade to upgrade): joblib in c:\anaconda\
lib\site-packages (from nolearn)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn in c:\ana
conda\lib\site-packages (from nolearn)
Requirement already satisfied (use --upgrade to upgrade): gnumpy in c:\anaconda\
lib\site-packages (from gdbn->nolearn)

C:\Users\Sander>pip install --upgrade nolearn
Requirement already up-to-date: nolearn in c:\anaconda\lib\site-packages
Requirement already up-to-date: gdbn in c:\anaconda\lib\site-packages (from nole
arn)
Requirement already up-to-date: docopt in c:\anaconda\lib\site-packages (from no
learn)
Collecting joblib (from nolearn)
  Downloading joblib-0.9.4-py2.py3-none-any.whl (112kB)
    100% |################################| 114kB 650kB/s
Collecting scikit-learn (from nolearn)
  Downloading scikit_learn-0.17.1-cp27-cp27m-win_amd64.whl (3.4MB)
    100% |################################| 3.4MB 129kB/s
Requirement already up-to-date: gnumpy in c:\anaconda\lib\site-packages (from gd
bn->nolearn)
Installing collected packages: joblib, scikit-learn
  Found existing installation: joblib 0.9.3
    Uninstalling joblib-0.9.3:
      Successfully uninstalled joblib-0.9.3
  Found existing installation: scikit-learn 0.14.1
    DEPRECATION: Uninstalling a distutils installed project (scikit-learn) has b
een deprecated and will be removed in a future version. This is due to the fact
that uninstalling a distutils project will only partially uninstall the project.

    Uninstalling scikit-learn-0.14.1:
      Successfully uninstalled scikit-learn-0.14.1
Successfully installed joblib-0.9.4 scikit-learn-0.16.1

C:\Users\Sander>

by the way I bought your book about math
to read about hessian free but actually there is nothing about it
I want to buy vol3 to read about recurrent NN
are there some serious material about rnns?

**Comment by jeffheaton** [comment]
It looks like it is an issue with the way Lasange is installed.  This link has more information:

https://github.com/dnouri/nolearn/issues/142

They have a link to the install instructions there.

**Comment by Sandy4321** [comment]
I very new lasagne

**Comment by jeffheaton** [comment]
Unfortunately, deep learning packages can be a bit of a pain to setup.  Lasange, Keras and the Theano based ones all require compiled C/C++ libraries which add complexity to the installation.  Tenso Flow is not too bad on Linux/Mac but difficult on Windows. Then if you add GPU it increases the installation complexity even more.  So for now I chose Lasange, but I might add Tensor Flow as an option soon.  

Let me know if the Lasange documents don't help you to get the environment working.  I've been meaning to do a "clean install" of Windows and document every step.  I realize the Lasange docs already sort of have this, but I might be able to make it a little clearer.

**Comment by Sandy4321** [comment]
I do use lasagne and it is ok
