### ISSUE TITLE
translation enquiry

### ISSUE THREAD

**Issue by anemochore** [jeffheaton/aifh#35]
Hi, my name is Sangbok Lee.
I work for Hanbit Media, one of the largest IT publisher in Korea
and I'm interested in translating your book into Korean and publishing in Korea.
I've tried to contact you via our copyright agency but they said there's no reply.
Can we talk a bit further? Please tell me how to contact you. Thank you.

**Comment by jeffheaton** [comment]
At this point I am not looking for translation partners.
